### PR TITLE
Update getting_started.md

### PR DESCRIPTION
**Pull request by robertOpt**

### CODE REVIEW

**Comment by robertOpt** [comment]
The proposed json file does no exist in this repository.  A similar json exists in the python Gerrychain repository, but the columns are different.  Please fix this tutorial so that it is easy to load an example.

**Comment by InnovativeInventor** [comment]
Thanks for contributing and pointing this out! Ideally this would run as-is, similar to the GerryChain Python [quickstart](https://gerrychain.readthedocs.io/en/latest/user/quickstart.html?highlight=pa_vtd#creating-the-initial-partition). 

I'm ok with you changing the variables to `TOTPOP` and `CD_2011` respectively (and adding a link to the PA VTD file) to bring it more in-line with the expectations of a quickstart tutorial.

**Review by InnovativeInventor — CHANGES_REQUESTED** [review]
Feel free to edit the code -- no need to leave these as in-line comments.

**Comment by robertOpt** [comment]
Thanks!  I'm actually having trouble getting it all working.  I keep
hitting errors.   Most recently with the districtscore functions.  I'll try
again and see if I can figure it out.

**Comment by InnovativeInventor** [comment]
Sounds good! If you need help, feel free to ask me -- I am available to meet as well. FYI, I've cherry-picked your commit in a separate PR that allows the quickstart to be run as-is.

**Pull request closed without merging**
